routes/web.php
<?php

use App\Http\Controllers\DealController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\StaffController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\TeacherController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [FrontendController::class, 'index'])->name('welcome');
Route::get('/register-form', [FrontendController::class, 'studentpdf'])->name('student.pdf');
Route::get('/employment-form', [FrontendController::class, 'teacherpdf'])->name('teacher.pdf');



Route::get('/dashboard/admin', function () {
    return view('backend.admin.index');
})->middleware(['auth'])->name('dashboard.admin');

    Route::resource('teachers', TeacherController::class);
    Route::resource('staffs', StaffController::class);

Route::get('/dashboard/principal', function () {
    return view('backend.principal.index');
})->middleware(['auth'])->name('dashboard.principal');

    Route::resource('deals', DealController::class);





Route::get('/dashboard/parent', function () {
    return view('backend.parent.index');
})->middleware(['auth'])->name('dashboard.parent');



Route::get('/dashboard/teacher', function () {
    return view('backend.teacher.index');
})->middleware(['auth'])->name('dashboard.teacher');

    Route::resource('teachers', TeacherController::class);


Route::get('/dashboard/student', function () {
    return view('backend.student.index');
})->middleware(['auth'])->name('dashboard.student');

    Route::resource('students', StudentController::class);

require __DIR__.'/auth.php';

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    use HasFactory;

    protected $fillable =[

        'student_name',
        'student_class',
        'email',
        'password',
        'father_name',
        'mother_name',
        'father_phone',
        'mother_phone',
        'date_of_birth',
        'gender',
        'adress',
    ];

    
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Student;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $students = Student::orderBy('id','desc')->get();
        
        return view('backend.student.crud.index',compact('students'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.student.crud.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data=$request->all();
       
        try 
        {
            Student::create(
                [
                'student_name'=>$data['student_name'],
                'student_class'=>$data['student_class'],
                'email'=>$data['email'],
                'password'=>$data['password'],
                'father_name'=>$data['father_name'],
                'father_phone'=>$data['father_phone'],
                'mother_name'=>$data['mother_name'],
                'mother_phone'=>$data['mother_phone'],
                'date_of_birth'=>$data['date_of_birth'],
                'gender'=>$data['gender'],
                'address'=>$data['address']
                ]);

                return redirect()->route('students.index')->withMessage('Successfully Saved !');

        } catch (QueryException $e)
        {
            // dd($ex);
        }
    
       
            // dd($request);

            return redirect()->route('backend.student.crud.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Student $student)
    {
        return view('backend.student.crud.show',compact('student'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Student $student)
    {
        return view('backend.student.crud.edit', compact('student'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Student $student)
    {
        $data=$request->all();

        $student->update([

            'student_name'=>$data['student_name'],
              'student_class'=>$data['student_class'],
              'email'=>$data['email'],
              'password'=>$data['password'],
              'father_name'=>$data['father_name'],
              'father_phone'=>$data['father_phone'],
               'mother_name'=>$data['mother_name'],
              'mother_phone'=>$data['mother_phone'],
              'date_of_birth'=>$data['date_of_birth'],
              'gender'=>$data['gender'],
                'address'=>$data['address']

        ]);
        return redirect()->route('students.index')->withMessage('Successfully Update!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Student $student)
    {
        $student->delete();
        return redirect()->route('students.index')->withMessage('Successfully Deleted !');
    }
}

resources/views/backend/student/crud/create.blade.php
<x-backend.student.layouts.master>

<div class="container">
<h1>Student Information</h1>
<form action="{{route('students.store')}}"method="post"style="justify-content: center;width: 100%; font-weight: bold;">
   @csrf

      <div class="row" style="margin-top:50px; margin-bottom: 10px;">
        <div class="col">
          <label>Student Name:</label>
          <input name="student_name" type="text" class="form-control" placeholder="Enter full name" aria-label="First name">
        </div>
        <div class="col">

          <label>Student Class  </label>
          <input name="student_class"type="text" class="form-control" placeholder="student class" >

        </div>
      </div>
      <div class="row" style="margin-bottom: 10px;">
        <div class="col">
          <label for=""> email:</label>
          <input name="email" type="email" class="form-control" >
        </div>
        <div class="col">
          <label>Password:</label>
          <input name="password"type="password" class="form-control" aria-label="password">
        </div>
      </div>
      <div class="row" style="margin-bottom: 10px;">
        <div class="col">
          <label for="">Father Name</label>
          <input name="father_name" type="text" class="form-control" aria-label="First name">
        </div>
        <div class="col">
          <label for="phone"> phone number</label>
          <input name="father_phone" type="number" class="form-control" placeholder="(+880)" aria-label="Last name">
        </div>
      </div>
      <div class="row" style="margin-bottom: 10px;">
        <div class="col">
          <label for="">Mother Name</label>
          <input name="mother_name"type="text" class="form-control" >
        </div>
        <div class="col">
          <label for="phone"> phone number</label>
          <input name="mother_phone" type="number" class="form-control" placeholder="(+880)" >
        </div>
      </div>

       <div class="row" style="margin: bottom 10px;">
      
      <div class="col">
          <label for="dateofbirth">Date of birth:</label>
          <div class="row">
            <input name="date_of_birth" type="date">
          </div>
      </div>
        <div class="col">
          <label for="gender">Gender:</label>
          <select name="gender" class="form-select" aria-label="Default select example" id="gender">
            <option selected>Select your Gender</option>
            <option value="male">Male</option>
            <option value="female">Female</option>
          </select>
        </div>
</div>

     
      <!-- <div class="row" style="margin-bottom: 10px;"> -->
        <div class="row ">
          <label for="adress">Adress:</label>
          <div class="row">
          
              <textarea name="address" id="" cols="50" rows="2"></textarea></div>
        
        </div>
      <div class="mb-3">
  <label for="formFile" class="form-label">Student Picture:</label>
  <input class="form-control" type="file" id="image">
</div>
      <div class="row justify-content-center">
        <div class="col-auto ">
          <button type="submit" class="btn btn-primary"
            style="width: 200px; font-weight: bold; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin-bottom: 50px; margin-top: 20px;">Submit</button>
  
        </div>
        <br>
      </div>
   
      
    



    </form>
</div>

</x-backend.student.layouts.master>

resources/views/backend/student/crud/edit.blade.php
<x-backend.student.layouts.master>
<div class="container">
<form action="{{route('students.update',['student'=>$student->id])}}" method="Post">

@csrf
@method('patch')

    
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<div class="row" style="margin-top:50px; margin-bottom: 10px;">
        <div class="col">
          <label>Student Name:</label>
          <input  value="{{$student->student_name}}" name="student_name" type="text" class="form-control" placeholder="Enter full name" aria-label="First name">
        </div>
        <div class="col">

          <label>Student Class  </label>
          <input value="{{$student->student_class}}"name="student_class"type="text" class="form-control" placeholder="student class" >

        </div>
      </div>
      <div class="row" style="margin-bottom: 10px;">
        <div class="col">
          <label for=""> email:</label>
          <input value="{{$student->email}}" name="email" type="email" class="form-control" >
        </div>
        <div class="col">
          <label>Password:</label>
          <input value="{{$student->password}}" name="password"type="password" class="form-control" aria-label="password">
        </div>
      </div>
      <div class="row" style="margin-bottom: 10px;">
        <div class="col">
          <label for="">Father Name</label>
          <input value="{{$student->father_name}}" name="father_name" type="text" class="form-control" aria-label="First name">
        </div>
        <div class="col">
          <label for="phone"> phone number</label>
          <input  value="{{$student->father_phone}}"name="father_phone" type="number" class="form-control" placeholder="(+880)" aria-label="Last name">
        </div>
      </div>
      <div class="row" style="margin-bottom: 10px;">
        <div class="col">
          <label for="">Mother Name</label>
          <input value="{{$student->mother_name}}" name="mother_name"type="text" class="form-control" >
        </div>
        <div class="col">
          <label for="phone"> phone number</label>
          <input value="{{$student->mother_phone}}" name="mother_phone" type="number" class="form-control" placeholder="(+880)" >
        </div>
      </div>

       <div class="row" style="margin: bottom 10px;">
      
      <div class="col">
          <label for="dateofbirth">Date of birth:</label>
          <div class="row">
            <input value="{{$student->date_of_birth}}" name="date_of_birth" type="date">
          </div>
      </div>
        <div class="col">
          <label for="gender">Gender:</label>
          <select name="gender" class="form-select" aria-label="Default select example" id="gender">
            <option selected>Select your Gender</option>
            <option value="male">Male</option>
            <option value="female">Female</option>
          </select>
        </div>
</div>

     
      <!-- <div class="row" style="margin-bottom: 10px;"> -->
        <div class="row ">
          <label for="address">Address:</label>
          <div class="row">
          
              <textarea value="{{$student->address}}" name="address" id="" cols="50" rows="2"></textarea></div>
        
        </div>
      <div class="mb-3">
  <label for="formFile" class="form-label">Student Picture:</label>
  <input class="form-control" type="file" id="image">
</div>
      <div class="row justify-content-center">
        <div class="col-auto ">
          <button type="submit" class="btn btn-primary"
            style="width: 200px; font-weight: bold; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin-bottom: 50px; margin-top: 20px;">Submit</button>
  
        </div>
        <br>
      </div>
   
      
    



    </form>
</div>
</x-backend.student.layouts.master>

resources/views/backend/student/crud/index.blade.php
<x-backend.student.layouts.master>

@if(Session::has('message'))
   <p class="text-danger">{{session::get('message')}}</p>
   @endif
<h3><a href="{{ route('dashboard.student') }}">Dashboard</a></h3><br> 
<h4><a href="{{ route('students.create') }}">Add Details</a></h4>
<table class='table table-striped' id="table1">
    <thead>
        <tr>
            <th scope="col">Sl</th>
            <th scope="col">Student Name</th>
            <th scope="col">Student Class</th>
            <th scope="col">email</th>
            <th scope="col">Father Number</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach($students as $student)
        <tr>
            <td>{{$loop->iteration}}</td>
            <td>{{$student->student_name}}</td>
            <td> {{$student->student_class}}</td>
            <td>{{$student->email}}</td>
            <td>{{$student->father_phone}}</td>

            <td><a  href="{{ route('students.show', ['student' => $student->id]) }}"class="btn btn-danger">Show</a>
            
            <a href="{{ route('students.edit', ['student' => $student->id]) }}"class="btn btn-warning">Edit</a>
            
            <form action="{{ route('students.destroy', ['student' => $student->id]) }}" method="post" style="display:inline">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-success" onclick="return confirm('Are you sure want to delete?')">Delete</button>
            </form>
            </td>
        </tr>
        @endforeach
                        
    </tbody>
</table>



</x-backend.student.layouts.master>

resources/views/backend/student/crud/show.blade.php
<x-backend.student.layouts.master>

    <h1 class="mt-4">Student</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
    </ol>

    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Product Details
            <a class="btn btn-sm btn-primary" href="{{ route('students.index') }}">Dashboard</a>
        </div>
        <div class="card-body">
            <h3>Name: {{ $student->student_name }}</h3>
            <h3>Class: {{ $student->student_class }}</h3>
            <p>Email: {{ $student->email }}</p>
            <p>Date of Birth: {{ $student->date_of_birth }}</p>
            <p>Gender: {{ $student->gender }}</p>
            <p>Father's Name: {{ $student->father_name }}</p>
            <p>Father's Phone: {{ $student->father_phone }}</p>
            <p>Mother's Name: {{ $student->mother_name }}</p>
            <p>Mother's Phone: {{ $student->mother_phone }}</p>
            <p>Address: {{ $student->address }}</p>
            
            
        </div>

    </div>

</x-backend.student.layouts.master>